export class EmployeeCotract{
    id:number
    contractStartDate:any
    duration:number
    unit:number
    contractualJob:string
    parties:string
    employmentStatusId:number
    employmentStatusName:string
    methodofContractingId:number
    methodofContractingName:string
    experimentEndDate:any
    employeeId:any
    contractTypeId:number
    contractTypeName:string
    isActivate:boolean
    ticketEntitlementFrequency:any
    ticketRoute:any
    ticketClassId:number
    ticketClassName:string
    annualVacationDaysId:any
    annualVacationDaysName:string
}