export class employeeDependents{
    id:number
    relationshipId:number
    relationshipName:string//
    titleId:number
    titleName:string
    firstNamePrimary:string//
    firstNameSecondary:string//
    fatherNamePrimary:string//
    fatherNameSecondary:string//
    grandFatherNamePrimary:string//
    grandFatherNameSecondary:string//
    familyNamePrimary:string//
    familyNameSecondary:string//
    genderId:number//
    genderName:string
    birthDate:string//
    civilIdentifierNumber:number//
    relationshipStartDate:string//
    eligibleforMedicalIn:boolean
    eligibleforTickets:boolean
    eligibleforSchool:boolean
    employeeId:any
}